# Generated by Django 3.1.4 on 2021-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('inventory', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
