# Generated by Django 3.1.4 on 2021-04-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0002_auto_20210410_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
